export type DropshipProduct = {
  title: string;
  body_html: string;
  vendor: string;
  product_type: string;
  tags: string[];
  price: string;
  compare_at_price: string;
  sku: string;
  weight: number;
  weight_unit: string;
  requires_shipping: boolean;
  inventory_quantity: number;
};

export const dropshipCatalog: DropshipProduct[] = [
  {
    title: 'Luxury Artificial Monstera Deliciosa — 90cm',
    body_html: '<p>Ultra-realistic faux Monstera Deliciosa with split-leaf detail. Hand-crafted silk leaves, weighted trunk. Perfect for living rooms, offices and retail spaces. Zero maintenance required.</p><ul><li>Height: 90cm</li><li>Material: Premium silk + ABS plastic</li><li>Pot included: Yes (ceramic white)</li><li>Ship from: EU Warehouse (NL)</li></ul>',
    vendor: 'FauxGreen EU',
    product_type: 'Artificial Plants',
    tags: ['monstera', 'large plant', 'silk', 'EU dropship', 'living room'],
    price: '49.99',
    compare_at_price: '79.99',
    sku: 'DS-MON-90-WH',
    weight: 1.8,
    weight_unit: 'kg',
    requires_shipping: true,
    inventory_quantity: 120,
  },
  {
    title: 'Trailing Faux Pothos Cascade Vine — 120cm',
    body_html: '<p>Beautiful trailing Pothos vine perfect for shelves, hanging baskets or macramé planters. Lush green leaves with natural colour variation. Looks stunning in any interior.</p><ul><li>Length: 120cm trailing</li><li>Material: High-quality silk</li><li>Pot/hanger: Not included</li><li>Ship from: EU Warehouse (NL)</li></ul>',
    vendor: 'FauxGreen EU',
    product_type: 'Artificial Plants',
    tags: ['pothos', 'trailing', 'vine', 'hanging plant', 'EU dropship'],
    price: '24.99',
    compare_at_price: '39.99',
    sku: 'DS-POT-120-GR',
    weight: 0.6,
    weight_unit: 'kg',
    requires_shipping: true,
    inventory_quantity: 200,
  },
  {
    title: 'Realistic Faux Snake Plant (Sansevieria) — 60cm',
    body_html: '<p>Architectural Sansevieria with ultra-realistic variegated leaves. A statement piece that suits every style — from minimalist to bohemian. Dust-wipe clean.</p><ul><li>Height: 60cm</li><li>Material: PE plastic + polyester</li><li>Pot: Terracotta finish included</li><li>Ship from: EU Warehouse (IE)</li></ul>',
    vendor: 'BotanicDrop IE',
    product_type: 'Artificial Plants',
    tags: ['snake plant', 'sansevieria', 'architectural', 'EU dropship', 'office'],
    price: '34.99',
    compare_at_price: '54.99',
    sku: 'DS-SAN-60-TC',
    weight: 1.2,
    weight_unit: 'kg',
    requires_shipping: true,
    inventory_quantity: 85,
  },
  {
    title: 'Faux Fiddle Leaf Fig Tree — 150cm',
    body_html: '<p>The iconic Fiddle Leaf Fig — now maintenance-free. Giant realistic leaves with natural vein detail. Single trunk design fits perfectly in corners and beside sofas.</p><ul><li>Height: 150cm</li><li>Material: Premium silk + natural wood trunk</li><li>Pot: White ceramic included</li><li>Ship from: EU Warehouse (NL)</li></ul>',
    vendor: 'FauxGreen EU',
    product_type: 'Artificial Trees',
    tags: ['fiddle leaf', 'fig tree', 'large', 'statement plant', 'EU dropship'],
    price: '89.99',
    compare_at_price: '139.99',
    sku: 'DS-FLF-150-WH',
    weight: 3.5,
    weight_unit: 'kg',
    requires_shipping: true,
    inventory_quantity: 40,
  },
  {
    title: 'Mini Faux Succulent Set — 6 Pack Assorted',
    body_html: '<p>Set of 6 adorable mini succulents in assorted styles — echeveria, cactus, sempervivum, aloe and more. Perfect for desks, windowsills and gift sets. Each in a terracotta mini pot.</p><ul><li>Height: 8–12cm each</li><li>Material: PE plastic</li><li>Pots: Terracotta mini pots included</li><li>Ship from: EU Warehouse (IE)</li></ul>',
    vendor: 'BotanicDrop IE',
    product_type: 'Artificial Succulents',
    tags: ['succulents', 'mini', 'set', 'desk plant', 'gift', 'EU dropship'],
    price: '22.99',
    compare_at_price: '34.99',
    sku: 'DS-SUC-6PK-TC',
    weight: 0.5,
    weight_unit: 'kg',
    requires_shipping: true,
    inventory_quantity: 300,
  },
  {
    title: 'Artificial Bamboo Stems Bundle — 10 Stems 80cm',
    body_html: '<p>Ten realistic bamboo stems with natural green coloring and node detail. Great for vases, floor arrangements and Asian-inspired decor. Combine with your own vessel.</p><ul><li>Height: 80cm</li><li>Material: Plastic + fabric</li><li>Vase not included</li><li>Ship from: EU Warehouse (NL)</li></ul>',
    vendor: 'FauxGreen EU',
    product_type: 'Artificial Stems',
    tags: ['bamboo', 'stems', 'bundle', 'asian decor', 'EU dropship'],
    price: '18.99',
    compare_at_price: '28.99',
    sku: 'DS-BAM-10-80',
    weight: 0.4,
    weight_unit: 'kg',
    requires_shipping: true,
    inventory_quantity: 180,
  },
  {
    title: 'Luxury Faux Orchid Arrangement — White Double Spike',
    body_html: '<p>Exquisite white Phalaenopsis orchid with double spike in a ceramic pot with moss filler. A timeless gift or accent piece. The most realistic faux orchid on the market.</p><ul><li>Height: 55cm</li><li>Blooms: 14 per spike</li><li>Pot: White ceramic + decorative moss</li><li>Ship from: EU Warehouse (IE)</li></ul>',
    vendor: 'BotanicDrop IE',
    product_type: 'Artificial Flowers',
    tags: ['orchid', 'white', 'flowers', 'gift', 'luxury', 'EU dropship'],
    price: '44.99',
    compare_at_price: '69.99',
    sku: 'DS-ORC-WH-DBL',
    weight: 0.9,
    weight_unit: 'kg',
    requires_shipping: true,
    inventory_quantity: 75,
  },
  {
    title: 'Faux Olive Tree with Natural Trunk — 120cm',
    body_html: '<p>Mediterranean-style faux olive tree with realistic natural trunk and delicate silver-green leaves. A showstopper for hallways, dining areas and retail displays.</p><ul><li>Height: 120cm</li><li>Material: Silk leaves + natural wood trunk</li><li>Pot: Woven rattan basket included</li><li>Ship from: EU Warehouse (NL)</li></ul>',
    vendor: 'FauxGreen EU',
    product_type: 'Artificial Trees',
    tags: ['olive tree', 'mediterranean', 'natural trunk', 'statement', 'EU dropship'],
    price: '74.99',
    compare_at_price: '119.99',
    sku: 'DS-OLV-120-RN',
    weight: 2.8,
    weight_unit: 'kg',
    requires_shipping: true,
    inventory_quantity: 55,
  },
  {
    title: 'Faux Hanging Eucalyptus Garland — 180cm',
    body_html: '<p>Lush eucalyptus garland with realistic leaf texture and natural green tones. Drape over mantels, archways, picture frames and tables. Wedding and event favourite.</p><ul><li>Length: 180cm</li><li>Material: Silk + wire core</li><li>Bendable and poseable</li><li>Ship from: EU Warehouse (IE)</li></ul>',
    vendor: 'BotanicDrop IE',
    product_type: 'Artificial Garlands',
    tags: ['eucalyptus', 'garland', 'wedding', 'decor', 'EU dropship'],
    price: '16.99',
    compare_at_price: '26.99',
    sku: 'DS-EUC-180-GR',
    weight: 0.3,
    weight_unit: 'kg',
    requires_shipping: true,
    inventory_quantity: 250,
  },
  {
    title: 'Realistic Faux Rubber Plant (Ficus Elastica) — 100cm',
    body_html: '<p>Bold burgundy and green rubber plant leaves with natural sheen. Architectural and modern — perfect for Scandinavian and contemporary interiors.</p><ul><li>Height: 100cm</li><li>Material: PE + polyester</li><li>Pot: Matte black ceramic included</li><li>Ship from: EU Warehouse (NL)</li></ul>',
    vendor: 'FauxGreen EU',
    product_type: 'Artificial Plants',
    tags: ['rubber plant', 'ficus', 'burgundy', 'modern', 'EU dropship'],
    price: '59.99',
    compare_at_price: '94.99',
    sku: 'DS-RUB-100-BK',
    weight: 2.1,
    weight_unit: 'kg',
    requires_shipping: true,
    inventory_quantity: 65,
  },
  {
    title: 'Artificial Peace Lily Bunch — 3 Stems 70cm',
    body_html: '<p>Graceful white Peace Lily with glossy green leaves. A classic for workspaces, bathrooms and shelving. Three stems with white spathe blooms ready to arrange.</p><ul><li>Height: 70cm per stem</li><li>Material: Silk + PE</li><li>Vase not included</li><li>Ship from: EU Warehouse (IE)</li></ul>',
    vendor: 'BotanicDrop IE',
    product_type: 'Artificial Flowers',
    tags: ['peace lily', 'white', 'flowers', 'workspace', 'EU dropship'],
    price: '19.99',
    compare_at_price: '31.99',
    sku: 'DS-PCL-3ST-WH',
    weight: 0.4,
    weight_unit: 'kg',
    requires_shipping: true,
    inventory_quantity: 160,
  },
  {
    title: 'Faux Calathea Orbifolia — 50cm',
    body_html: '<p>Stunning round-leaved Calathea Orbifolia with silver-green pinstripe pattern. One of the most sought-after houseplants — now zero-care. Great for bathrooms and bedrooms.</p><ul><li>Height: 50cm</li><li>Material: High-quality silk</li><li>Pot: Terracotta cream included</li><li>Ship from: EU Warehouse (NL)</li></ul>',
    vendor: 'FauxGreen EU',
    product_type: 'Artificial Plants',
    tags: ['calathea', 'orbifolia', 'bathroom', 'bedroom', 'EU dropship'],
    price: '39.99',
    compare_at_price: '64.99',
    sku: 'DS-CAL-50-CR',
    weight: 0.8,
    weight_unit: 'kg',
    requires_shipping: true,
    inventory_quantity: 90,
  },
];
